name: elearnia_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.2.0   # pour Face ID / empreinte plus tard
  cupertino_icons: ^1.0.8
  video_player: ^2.8.2
  youtube_player_flutter: ^9.0.2
  url_launcher: ^6.2.4
  chewie: ^1.7.4
  image_picker: ^1.0.7
  mime: ^1.0.4
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.6.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  ionicons: ^0.2.2
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
